# Generated by Django 4.0.1 on 2023-04-24 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipient',
            old_name='name',
            new_name='recipient',
        ),
        migrations.RenameField(
            model_name='sender',
            old_name='name',
            new_name='sender',
        ),
    ]
