# Generated by Django 4.0.1 on 2023-04-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient_id',
            new_name='recipient_id_id',
        ),
    ]
